// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/entity.Airport
type EntityAirport struct {
	Iata         string         `json:"iata"`
	Location     EntityLocation `json:"location"`
	Municipality string         `json:"municipality"`
	Name         string         `json:"name"`
}

// GetIata returns the value of Iata.
func (s *EntityAirport) GetIata() string {
	return s.Iata
}

// GetLocation returns the value of Location.
func (s *EntityAirport) GetLocation() EntityLocation {
	return s.Location
}

// GetMunicipality returns the value of Municipality.
func (s *EntityAirport) GetMunicipality() string {
	return s.Municipality
}

// GetName returns the value of Name.
func (s *EntityAirport) GetName() string {
	return s.Name
}

// SetIata sets the value of Iata.
func (s *EntityAirport) SetIata(val string) {
	s.Iata = val
}

// SetLocation sets the value of Location.
func (s *EntityAirport) SetLocation(val EntityLocation) {
	s.Location = val
}

// SetMunicipality sets the value of Municipality.
func (s *EntityAirport) SetMunicipality(val string) {
	s.Municipality = val
}

// SetName sets the value of Name.
func (s *EntityAirport) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/entity.AmbiguousFlightChoice
type EntityAmbiguousFlightChoice struct {
	DepartureDateTime string `json:"departureDateTime"`
	DestinationIata   string `json:"destinationIata"`
	OriginIata        string `json:"originIata"`
}

// GetDepartureDateTime returns the value of DepartureDateTime.
func (s *EntityAmbiguousFlightChoice) GetDepartureDateTime() string {
	return s.DepartureDateTime
}

// GetDestinationIata returns the value of DestinationIata.
func (s *EntityAmbiguousFlightChoice) GetDestinationIata() string {
	return s.DestinationIata
}

// GetOriginIata returns the value of OriginIata.
func (s *EntityAmbiguousFlightChoice) GetOriginIata() string {
	return s.OriginIata
}

// SetDepartureDateTime sets the value of DepartureDateTime.
func (s *EntityAmbiguousFlightChoice) SetDepartureDateTime(val string) {
	s.DepartureDateTime = val
}

// SetDestinationIata sets the value of DestinationIata.
func (s *EntityAmbiguousFlightChoice) SetDestinationIata(val string) {
	s.DestinationIata = val
}

// SetOriginIata sets the value of OriginIata.
func (s *EntityAmbiguousFlightChoice) SetOriginIata(val string) {
	s.OriginIata = val
}

// Ref: #/components/schemas/entity.ErrAmbiguousFlightRequest
type EntityErrAmbiguousFlightRequest map[string][]EntityAmbiguousFlightChoice

func (s *EntityErrAmbiguousFlightRequest) init() EntityErrAmbiguousFlightRequest {
	m := *s
	if m == nil {
		m = map[string][]EntityAmbiguousFlightChoice{}
		*s = m
	}
	return m
}

func (*EntityErrAmbiguousFlightRequest) postFlightRes() {}

// Ref: #/components/schemas/entity.Flight
type EntityFlight struct {
	Legs []EntityFlightLeg `json:"legs"`
}

// GetLegs returns the value of Legs.
func (s *EntityFlight) GetLegs() []EntityFlightLeg {
	return s.Legs
}

// SetLegs sets the value of Legs.
func (s *EntityFlight) SetLegs(val []EntityFlightLeg) {
	s.Legs = val
}

func (*EntityFlight) postFlightRes() {}

// Ref: #/components/schemas/entity.FlightLeg
type EntityFlightLeg struct {
	Aircraft          NilString     `json:"aircraft"`
	Airline           string        `json:"airline"`
	AmadeusFlightDate NilString     `json:"amadeusFlightDate"`
	ArrivalDateTime   string        `json:"arrivalDateTime"`
	DepartureDateTime string        `json:"departureDateTime"`
	Destination       EntityAirport `json:"destination"`
	DurationInMinutes int           `json:"durationInMinutes"`
	FlightNumber      string        `json:"flightNumber"`
	Origin            EntityAirport `json:"origin"`
}

// GetAircraft returns the value of Aircraft.
func (s *EntityFlightLeg) GetAircraft() NilString {
	return s.Aircraft
}

// GetAirline returns the value of Airline.
func (s *EntityFlightLeg) GetAirline() string {
	return s.Airline
}

// GetAmadeusFlightDate returns the value of AmadeusFlightDate.
func (s *EntityFlightLeg) GetAmadeusFlightDate() NilString {
	return s.AmadeusFlightDate
}

// GetArrivalDateTime returns the value of ArrivalDateTime.
func (s *EntityFlightLeg) GetArrivalDateTime() string {
	return s.ArrivalDateTime
}

// GetDepartureDateTime returns the value of DepartureDateTime.
func (s *EntityFlightLeg) GetDepartureDateTime() string {
	return s.DepartureDateTime
}

// GetDestination returns the value of Destination.
func (s *EntityFlightLeg) GetDestination() EntityAirport {
	return s.Destination
}

// GetDurationInMinutes returns the value of DurationInMinutes.
func (s *EntityFlightLeg) GetDurationInMinutes() int {
	return s.DurationInMinutes
}

// GetFlightNumber returns the value of FlightNumber.
func (s *EntityFlightLeg) GetFlightNumber() string {
	return s.FlightNumber
}

// GetOrigin returns the value of Origin.
func (s *EntityFlightLeg) GetOrigin() EntityAirport {
	return s.Origin
}

// SetAircraft sets the value of Aircraft.
func (s *EntityFlightLeg) SetAircraft(val NilString) {
	s.Aircraft = val
}

// SetAirline sets the value of Airline.
func (s *EntityFlightLeg) SetAirline(val string) {
	s.Airline = val
}

// SetAmadeusFlightDate sets the value of AmadeusFlightDate.
func (s *EntityFlightLeg) SetAmadeusFlightDate(val NilString) {
	s.AmadeusFlightDate = val
}

// SetArrivalDateTime sets the value of ArrivalDateTime.
func (s *EntityFlightLeg) SetArrivalDateTime(val string) {
	s.ArrivalDateTime = val
}

// SetDepartureDateTime sets the value of DepartureDateTime.
func (s *EntityFlightLeg) SetDepartureDateTime(val string) {
	s.DepartureDateTime = val
}

// SetDestination sets the value of Destination.
func (s *EntityFlightLeg) SetDestination(val EntityAirport) {
	s.Destination = val
}

// SetDurationInMinutes sets the value of DurationInMinutes.
func (s *EntityFlightLeg) SetDurationInMinutes(val int) {
	s.DurationInMinutes = val
}

// SetFlightNumber sets the value of FlightNumber.
func (s *EntityFlightLeg) SetFlightNumber(val string) {
	s.FlightNumber = val
}

// SetOrigin sets the value of Origin.
func (s *EntityFlightLeg) SetOrigin(val EntityAirport) {
	s.Origin = val
}

// Ref: #/components/schemas/entity.Location
type EntityLocation struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// GetLatitude returns the value of Latitude.
func (s *EntityLocation) GetLatitude() float64 {
	return s.Latitude
}

// GetLongitude returns the value of Longitude.
func (s *EntityLocation) GetLongitude() float64 {
	return s.Longitude
}

// SetLatitude sets the value of Latitude.
func (s *EntityLocation) SetLatitude(val float64) {
	s.Latitude = val
}

// SetLongitude sets the value of Longitude.
func (s *EntityLocation) SetLongitude(val float64) {
	s.Longitude = val
}

func (*EntityLocation) lookupLocationRes() {}

// Ref: #/components/schemas/entity.Train
type EntityTrain struct {
	Legs         []EntityTrainLeg `json:"legs"`
	RefreshToken string           `json:"refreshToken"`
}

// GetLegs returns the value of Legs.
func (s *EntityTrain) GetLegs() []EntityTrainLeg {
	return s.Legs
}

// GetRefreshToken returns the value of RefreshToken.
func (s *EntityTrain) GetRefreshToken() string {
	return s.RefreshToken
}

// SetLegs sets the value of Legs.
func (s *EntityTrain) SetLegs(val []EntityTrainLeg) {
	s.Legs = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *EntityTrain) SetRefreshToken(val string) {
	s.RefreshToken = val
}

func (*EntityTrain) postTrainJourneyRes() {}

// Ref: #/components/schemas/entity.TrainLeg
type EntityTrainLeg struct {
	ArrivalDateTime   string             `json:"arrivalDateTime"`
	DepartureDateTime string             `json:"departureDateTime"`
	Destination       EntityTrainStation `json:"destination"`
	DurationInMinutes int                `json:"durationInMinutes"`
	LineName          string             `json:"lineName"`
	OperatorName      string             `json:"operatorName"`
	Origin            EntityTrainStation `json:"origin"`
}

// GetArrivalDateTime returns the value of ArrivalDateTime.
func (s *EntityTrainLeg) GetArrivalDateTime() string {
	return s.ArrivalDateTime
}

// GetDepartureDateTime returns the value of DepartureDateTime.
func (s *EntityTrainLeg) GetDepartureDateTime() string {
	return s.DepartureDateTime
}

// GetDestination returns the value of Destination.
func (s *EntityTrainLeg) GetDestination() EntityTrainStation {
	return s.Destination
}

// GetDurationInMinutes returns the value of DurationInMinutes.
func (s *EntityTrainLeg) GetDurationInMinutes() int {
	return s.DurationInMinutes
}

// GetLineName returns the value of LineName.
func (s *EntityTrainLeg) GetLineName() string {
	return s.LineName
}

// GetOperatorName returns the value of OperatorName.
func (s *EntityTrainLeg) GetOperatorName() string {
	return s.OperatorName
}

// GetOrigin returns the value of Origin.
func (s *EntityTrainLeg) GetOrigin() EntityTrainStation {
	return s.Origin
}

// SetArrivalDateTime sets the value of ArrivalDateTime.
func (s *EntityTrainLeg) SetArrivalDateTime(val string) {
	s.ArrivalDateTime = val
}

// SetDepartureDateTime sets the value of DepartureDateTime.
func (s *EntityTrainLeg) SetDepartureDateTime(val string) {
	s.DepartureDateTime = val
}

// SetDestination sets the value of Destination.
func (s *EntityTrainLeg) SetDestination(val EntityTrainStation) {
	s.Destination = val
}

// SetDurationInMinutes sets the value of DurationInMinutes.
func (s *EntityTrainLeg) SetDurationInMinutes(val int) {
	s.DurationInMinutes = val
}

// SetLineName sets the value of LineName.
func (s *EntityTrainLeg) SetLineName(val string) {
	s.LineName = val
}

// SetOperatorName sets the value of OperatorName.
func (s *EntityTrainLeg) SetOperatorName(val string) {
	s.OperatorName = val
}

// SetOrigin sets the value of Origin.
func (s *EntityTrainLeg) SetOrigin(val EntityTrainStation) {
	s.Origin = val
}

// Ref: #/components/schemas/entity.TrainStation
type EntityTrainStation struct {
	ID       string         `json:"id"`
	Location EntityLocation `json:"location"`
	Name     string         `json:"name"`
}

// GetID returns the value of ID.
func (s *EntityTrainStation) GetID() string {
	return s.ID
}

// GetLocation returns the value of Location.
func (s *EntityTrainStation) GetLocation() EntityLocation {
	return s.Location
}

// GetName returns the value of Name.
func (s *EntityTrainStation) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *EntityTrainStation) SetID(val string) {
	s.ID = val
}

// SetLocation sets the value of Location.
func (s *EntityTrainStation) SetLocation(val EntityLocation) {
	s.Location = val
}

// SetName sets the value of Name.
func (s *EntityTrainStation) SetName(val string) {
	s.Name = val
}

func (*EntityTrainStation) lookupTrainStationRes() {}

type EntityTransportationType string

type LookupDirectionsBadRequest ResponseError

func (*LookupDirectionsBadRequest) lookupDirectionsRes() {}

type LookupDirectionsInternalServerError ResponseError

func (*LookupDirectionsInternalServerError) lookupDirectionsRes() {}

type LookupDirectionsOKApplicationJSON string

func (*LookupDirectionsOKApplicationJSON) lookupDirectionsRes() {}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/request.Directions
type RequestDirections struct {
	End                EntityLocation           `json:"end"`
	Start              EntityLocation           `json:"start"`
	TransportationType EntityTransportationType `json:"transportationType"`
}

// GetEnd returns the value of End.
func (s *RequestDirections) GetEnd() EntityLocation {
	return s.End
}

// GetStart returns the value of Start.
func (s *RequestDirections) GetStart() EntityLocation {
	return s.Start
}

// GetTransportationType returns the value of TransportationType.
func (s *RequestDirections) GetTransportationType() EntityTransportationType {
	return s.TransportationType
}

// SetEnd sets the value of End.
func (s *RequestDirections) SetEnd(val EntityLocation) {
	s.End = val
}

// SetStart sets the value of Start.
func (s *RequestDirections) SetStart(val EntityLocation) {
	s.Start = val
}

// SetTransportationType sets the value of TransportationType.
func (s *RequestDirections) SetTransportationType(val EntityTransportationType) {
	s.TransportationType = val
}

// Ref: #/components/schemas/request.Flight
type RequestFlight struct {
	Legs []RequestFlightLeg `json:"legs"`
}

// GetLegs returns the value of Legs.
func (s *RequestFlight) GetLegs() []RequestFlightLeg {
	return s.Legs
}

// SetLegs sets the value of Legs.
func (s *RequestFlight) SetLegs(val []RequestFlightLeg) {
	s.Legs = val
}

// Ref: #/components/schemas/request.FlightLeg
type RequestFlightLeg struct {
	Date          string    `json:"date"`
	FlightNumber  string    `json:"flightNumber"`
	OriginAirport NilString `json:"originAirport"`
}

// GetDate returns the value of Date.
func (s *RequestFlightLeg) GetDate() string {
	return s.Date
}

// GetFlightNumber returns the value of FlightNumber.
func (s *RequestFlightLeg) GetFlightNumber() string {
	return s.FlightNumber
}

// GetOriginAirport returns the value of OriginAirport.
func (s *RequestFlightLeg) GetOriginAirport() NilString {
	return s.OriginAirport
}

// SetDate sets the value of Date.
func (s *RequestFlightLeg) SetDate(val string) {
	s.Date = val
}

// SetFlightNumber sets the value of FlightNumber.
func (s *RequestFlightLeg) SetFlightNumber(val string) {
	s.FlightNumber = val
}

// SetOriginAirport sets the value of OriginAirport.
func (s *RequestFlightLeg) SetOriginAirport(val NilString) {
	s.OriginAirport = val
}

// Ref: #/components/schemas/request.Train
type RequestTrain struct {
	DepartureDate string    `json:"departureDate"`
	FromStationId string    `json:"fromStationId"`
	ToStationId   string    `json:"toStationId"`
	TrainNumbers  []string  `json:"trainNumbers"`
	ViaStationId  NilString `json:"viaStationId"`
}

// GetDepartureDate returns the value of DepartureDate.
func (s *RequestTrain) GetDepartureDate() string {
	return s.DepartureDate
}

// GetFromStationId returns the value of FromStationId.
func (s *RequestTrain) GetFromStationId() string {
	return s.FromStationId
}

// GetToStationId returns the value of ToStationId.
func (s *RequestTrain) GetToStationId() string {
	return s.ToStationId
}

// GetTrainNumbers returns the value of TrainNumbers.
func (s *RequestTrain) GetTrainNumbers() []string {
	return s.TrainNumbers
}

// GetViaStationId returns the value of ViaStationId.
func (s *RequestTrain) GetViaStationId() NilString {
	return s.ViaStationId
}

// SetDepartureDate sets the value of DepartureDate.
func (s *RequestTrain) SetDepartureDate(val string) {
	s.DepartureDate = val
}

// SetFromStationId sets the value of FromStationId.
func (s *RequestTrain) SetFromStationId(val string) {
	s.FromStationId = val
}

// SetToStationId sets the value of ToStationId.
func (s *RequestTrain) SetToStationId(val string) {
	s.ToStationId = val
}

// SetTrainNumbers sets the value of TrainNumbers.
func (s *RequestTrain) SetTrainNumbers(val []string) {
	s.TrainNumbers = val
}

// SetViaStationId sets the value of ViaStationId.
func (s *RequestTrain) SetViaStationId(val NilString) {
	s.ViaStationId = val
}

// Ref: #/components/schemas/response.Error
type ResponseError struct {
	Detail OptNilString `json:"detail"`
	Error  string       `json:"error"`
}

// GetDetail returns the value of Detail.
func (s *ResponseError) GetDetail() OptNilString {
	return s.Detail
}

// GetError returns the value of Error.
func (s *ResponseError) GetError() string {
	return s.Error
}

// SetDetail sets the value of Detail.
func (s *ResponseError) SetDetail(val OptNilString) {
	s.Detail = val
}

// SetError sets the value of Error.
func (s *ResponseError) SetError(val string) {
	s.Error = val
}

func (*ResponseError) lookupLocationRes()     {}
func (*ResponseError) lookupTrainStationRes() {}
func (*ResponseError) postFlightRes()         {}
func (*ResponseError) postTrainJourneyRes()   {}
