// Code generated by ogen, DO NOT EDIT.
package api

type LookupDirectionsRes interface {
	lookupDirectionsRes()
}

type LookupLocationRes interface {
	lookupLocationRes()
}

type LookupTrainStationRes interface {
	lookupTrainStationRes()
}

type PostFlightRes interface {
	postFlightRes()
}

type PostTrainJourneyRes interface {
	postTrainJourneyRes()
}
