// Code generated by ogen, DO NOT EDIT.

package api

// LookupLocationParams is parameters of lookupLocation operation.
type LookupLocationParams struct {
	// Location query.
	Query string
}

// LookupTrainStationParams is parameters of lookupTrainStation operation.
type LookupTrainStationParams struct {
	// Station query.
	Query string
}
