// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	LookupDirectionsOperation   OperationName = "LookupDirections"
	LookupLocationOperation     OperationName = "LookupLocation"
	LookupTrainStationOperation OperationName = "LookupTrainStation"
	PostFlightOperation         OperationName = "PostFlight"
	PostTrainJourneyOperation   OperationName = "PostTrainJourney"
)
