/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripRouteImport } from './routes/$trip'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripIndexRouteImport } from './routes/$trip/index'
import { Route as TripShareRouteImport } from './routes/$trip/share'
import { Route as TripNotesRouteImport } from './routes/$trip/notes'
import { Route as TripMapRouteImport } from './routes/$trip/map'
import { Route as TripItineraryRouteImport } from './routes/$trip/itinerary'

const TripRoute = TripRouteImport.update({
  id: '/$trip',
  path: '/$trip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIndexRoute = TripIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripRoute,
} as any)
const TripShareRoute = TripShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => TripRoute,
} as any)
const TripNotesRoute = TripNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TripRoute,
} as any)
const TripMapRoute = TripMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => TripRoute,
} as any)
const TripItineraryRoute = TripItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => TripRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$trip': typeof TripRouteWithChildren
  '/$trip/itinerary': typeof TripItineraryRoute
  '/$trip/map': typeof TripMapRoute
  '/$trip/notes': typeof TripNotesRoute
  '/$trip/share': typeof TripShareRoute
  '/$trip/': typeof TripIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$trip/itinerary': typeof TripItineraryRoute
  '/$trip/map': typeof TripMapRoute
  '/$trip/notes': typeof TripNotesRoute
  '/$trip/share': typeof TripShareRoute
  '/$trip': typeof TripIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$trip': typeof TripRouteWithChildren
  '/$trip/itinerary': typeof TripItineraryRoute
  '/$trip/map': typeof TripMapRoute
  '/$trip/notes': typeof TripNotesRoute
  '/$trip/share': typeof TripShareRoute
  '/$trip/': typeof TripIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$trip'
    | '/$trip/itinerary'
    | '/$trip/map'
    | '/$trip/notes'
    | '/$trip/share'
    | '/$trip/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$trip/itinerary'
    | '/$trip/map'
    | '/$trip/notes'
    | '/$trip/share'
    | '/$trip'
  id:
    | '__root__'
    | '/'
    | '/$trip'
    | '/$trip/itinerary'
    | '/$trip/map'
    | '/$trip/notes'
    | '/$trip/share'
    | '/$trip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripRoute: typeof TripRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$trip': {
      id: '/$trip'
      path: '/$trip'
      fullPath: '/$trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trip/': {
      id: '/$trip/'
      path: '/'
      fullPath: '/$trip/'
      preLoaderRoute: typeof TripIndexRouteImport
      parentRoute: typeof TripRoute
    }
    '/$trip/share': {
      id: '/$trip/share'
      path: '/share'
      fullPath: '/$trip/share'
      preLoaderRoute: typeof TripShareRouteImport
      parentRoute: typeof TripRoute
    }
    '/$trip/notes': {
      id: '/$trip/notes'
      path: '/notes'
      fullPath: '/$trip/notes'
      preLoaderRoute: typeof TripNotesRouteImport
      parentRoute: typeof TripRoute
    }
    '/$trip/map': {
      id: '/$trip/map'
      path: '/map'
      fullPath: '/$trip/map'
      preLoaderRoute: typeof TripMapRouteImport
      parentRoute: typeof TripRoute
    }
    '/$trip/itinerary': {
      id: '/$trip/itinerary'
      path: '/itinerary'
      fullPath: '/$trip/itinerary'
      preLoaderRoute: typeof TripItineraryRouteImport
      parentRoute: typeof TripRoute
    }
  }
}

interface TripRouteChildren {
  TripItineraryRoute: typeof TripItineraryRoute
  TripMapRoute: typeof TripMapRoute
  TripNotesRoute: typeof TripNotesRoute
  TripShareRoute: typeof TripShareRoute
  TripIndexRoute: typeof TripIndexRoute
}

const TripRouteChildren: TripRouteChildren = {
  TripItineraryRoute: TripItineraryRoute,
  TripMapRoute: TripMapRoute,
  TripNotesRoute: TripNotesRoute,
  TripShareRoute: TripShareRoute,
  TripIndexRoute: TripIndexRoute,
}

const TripRouteWithChildren = TripRoute._addFileChildren(TripRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripRoute: TripRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
